# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Octa476/Desktop/Random_generator_module/Nexys4DDR_Master.xdc

# Block Designs: bd/design_random/design_random.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random || ORIG_REF_NAME==design_random} -quiet] -quiet

# IP: bd/design_random/ip/design_random_nand_module_0_0/design_random_nand_module_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_nand_module_0_0 || ORIG_REF_NAME==design_random_nand_module_0_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_nand_module_1_0/design_random_nand_module_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_nand_module_1_0 || ORIG_REF_NAME==design_random_nand_module_1_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_nand_module_2_0/design_random_nand_module_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_nand_module_2_0 || ORIG_REF_NAME==design_random_nand_module_2_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_nand_module_3_0/design_random_nand_module_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_nand_module_3_0 || ORIG_REF_NAME==design_random_nand_module_3_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_xor_4_0_0/design_random_xor_4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_xor_4_0_0 || ORIG_REF_NAME==design_random_xor_4_0_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_nand_module_5_0/design_random_nand_module_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_nand_module_5_0 || ORIG_REF_NAME==design_random_nand_module_5_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_nand_module_6_0/design_random_nand_module_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_nand_module_6_0 || ORIG_REF_NAME==design_random_nand_module_6_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_xor_3_0_0/design_random_xor_3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_xor_3_0_0 || ORIG_REF_NAME==design_random_xor_3_0_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_dff_module1_0_0/design_random_dff_module1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_dff_module1_0_0 || ORIG_REF_NAME==design_random_dff_module1_0_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_dff_module1_1_0/design_random_dff_module1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_dff_module1_1_0 || ORIG_REF_NAME==design_random_dff_module1_1_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_dff_module1_2_0/design_random_dff_module1_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_dff_module1_2_0 || ORIG_REF_NAME==design_random_dff_module1_2_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_dff_module1_3_0/design_random_dff_module1_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_dff_module1_3_0 || ORIG_REF_NAME==design_random_dff_module1_3_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_dff_module1_4_0/design_random_dff_module1_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_dff_module1_4_0 || ORIG_REF_NAME==design_random_dff_module1_4_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_dff_module1_5_0/design_random_dff_module1_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_dff_module1_5_0 || ORIG_REF_NAME==design_random_dff_module1_5_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_dff_module1_6_0/design_random_dff_module1_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_dff_module1_6_0 || ORIG_REF_NAME==design_random_dff_module1_6_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_0_0/design_random_inverter_real_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_0_0 || ORIG_REF_NAME==design_random_inverter_real_0_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_1_0/design_random_inverter_real_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_1_0 || ORIG_REF_NAME==design_random_inverter_real_1_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_2_0/design_random_inverter_real_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_2_0 || ORIG_REF_NAME==design_random_inverter_real_2_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_3_0/design_random_inverter_real_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_3_0 || ORIG_REF_NAME==design_random_inverter_real_3_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_4_0/design_random_inverter_real_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_4_0 || ORIG_REF_NAME==design_random_inverter_real_4_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_5_0/design_random_inverter_real_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_5_0 || ORIG_REF_NAME==design_random_inverter_real_5_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_6_0/design_random_inverter_real_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_6_0 || ORIG_REF_NAME==design_random_inverter_real_6_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_7_0/design_random_inverter_real_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_7_0 || ORIG_REF_NAME==design_random_inverter_real_7_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_8_0/design_random_inverter_real_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_8_0 || ORIG_REF_NAME==design_random_inverter_real_8_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_9_0/design_random_inverter_real_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_9_0 || ORIG_REF_NAME==design_random_inverter_real_9_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_10_0/design_random_inverter_real_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_10_0 || ORIG_REF_NAME==design_random_inverter_real_10_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_11_0/design_random_inverter_real_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_11_0 || ORIG_REF_NAME==design_random_inverter_real_11_0} -quiet] -quiet

# IP: bd/design_random/ip/design_random_inverter_real_12_0/design_random_inverter_real_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_random_inverter_real_12_0 || ORIG_REF_NAME==design_random_inverter_real_12_0} -quiet] -quiet

# XDC: c:/Users/Octa476/Desktop/Random_generator_module/random_generator_project_synt/random_generator_project.gen/sources_1/bd/design_random/design_random_ooc.xdc
